-- liquibase formatted sql
--
-- changeset script:1
-- comment: Creation table clientes
--
create table clientes (id bigint generated by default as identity, apellido varchar(255), nombre varchar(255), telefono varchar(255), primary key (id));
--
-- changeset script:2
-- comment: Creation table reserva
create table reserva (id bigint generated by default as identity, hora_fin timestamp(6), hora_inicio timestamp(6), cliente_id bigint, primary key (id));
--
-- changeset script:3
-- comment: Creation estado facturas
create table estado (id bigint generated by default as identity, descripcion varchar(255), primary key (id));
--
-- changeset script:6
-- comment: Creation table facturas
insert into clientes (nombre, apellido, telefono) values
    ( 'Luisa', 'Castro', '3256985263' ),
    ( 'Luis', 'Bermudez', '3233386589' );
--
-- changeset script:7
-- comment: Creation table detalles
insert into estado (descripcion) values
    ( 'Agendada' ),
    ( 'En proceso' ),
    ( 'Terminada' );